### ISSUE TITLE
Add the new lib-http 3.0 Beta to lib-nextjs-proxy

### ISSUE THREAD

**Issue by pmi** [enonic/nextjs-enonic-demo#210]

**Comment by pmi** [comment]
Gives error `java.lang.IllegalArgumentException: unsupported URI http:/localhost:3000/`

**Comment by sigdestad** [comment]
Ok, we'll skip it for now then - can you give feedback to SRY about this issue?

**Comment by sigdestad** [comment]
Tell that to the developer running our SDK :-)

**Comment by rymsha** [comment]
I'm not sure I get the joke...

`http://localhost:3000/` would be correct.

**Comment by sigdestad** [comment]
Ah, did not see the single slash, @pmi?
