### ISSUE TITLE
Feedback nextjs tutorial

### ISSUE THREAD

**Issue by poi33** [enonic/nextjs-enonic-demo#218]
Chapter 1 - Setting up Enonic
Headless movie database

[Task: Create application from template](https://developer.enonic.com/docs/next.xp/master/enonic-setup#task_create_application_from_template)
3. Deploy the application locally
The command `enonic project deploy` will not work since they just created a folder, and not inside it. 
`cd myproject` and then `enonic project deploy`

4. Install and test Content Studio. 
> Navigate to http://localhost:8080/ Select admin, and log in (you don’t have to create a user for this tutorial). 

`Select admin` ? What is Select admin? Just shorten it to Go to http://localhost:8080 and log in to the system.

> From the XP menu, open Content Studio, and choose the HMDB project if asked.

The project is called `Headless Demo` when i just installed it?

Chapter 4. Rendering basics
[Task: Add custom header and footer](https://developer.enonic.com/docs/next.xp/master/rendering-basics#task_add_custom_header_and_footer)

> 1.Add these imports
```
import Header from "../components/views/Header";
import Footer from "../components/views/Footer";
import {getUrl} from "../_enonicAdapter/utils";
```

The last line import {getUrl} is allready included in the code

> chapter 5. preview 
Getting errors when setting up the intended mapping in site.xml

**Comment by poi33** [comment]
Chapter 7.
[Task: Add part to Enonic](https://developer.enonic.com/docs/next.xp/master/parts#task_add_part_to_enonic)
4. Add parts to the page
> After the app has deployed, head over to Content Studio. This time, lets edit the Persons page.

There is no person page. Only a person folder.

**Comment by sigdestad** [comment]
All issues above have been resolved
