### ISSUE TITLE
Visiting site via header icon link will change browser history/location

### ISSUE THREAD

**Issue by sigdestad** [enonic/nextjs-enonic-demo#253]
Links are correct and work fine both in next directly, and in preview - however, clicking the link in preview will render the front-page, but change the browser url to just localhost:8080 ?

Investigate why this is happening

**Comment by pmi** [comment]
Doesn't seem to be an issue any more for all of the pages, except for the 404 page where it just points to itself.
But links on page 404 should be fixed in https://github.com/enonic/nextjs-adapter/issues/87
