### ISSUE TITLE
Possible to change the part query

### ISSUE THREAD

**Issue by poi33** [enonic/nextjs-enonic-demo#296]
Currently when you get the props of a part the data is fixed. 

/components/parts/myPart.tsx
```
const MyPart = (props: PartProps) => {
    const {config} = props.part;
    [...]
}
```

Will get the configuration of the part, but not option to add or change the graphql query.

Lets say we have an imageSelector in the config: 
```
{
    "image": "d390a23d-5aa6-4c8c-8827-aed2e333f330",
} 
```
Its not possible to get the imageUrl on the initial query done when rendering the part.
Could there be added a way to change the query that returns the part config?

**Comment by poi33** [comment]
This will probably be the same for layouts with configuration. 
They would also have the same issue, if the layouts query is the default one only

**Comment by alansemenov** [comment]
Implemented in https://github.com/enonic/nextjs-enonic-demo/issues/326
