### ISSUE TITLE
Component paths get wrong index

### ISSUE THREAD

**Issue by poi33** [enonic/nextjs-enonic-demo#307]
Having the same region name in a layout and page controller gets the wrong index
 
https://github.com/enonic/nextjs-enonic-demo/blob/bea85e9caf4efaa4a0c0fe38c096a5b8d18a9f37/src/_enonicAdapter/guillotine/fetchContent.ts#L381-L384

Log of region index and paths: 
```
index: 0
path : /main/8/main/0
---
index: 0
path: /main/9/main/0
---
```
I have a main region in my layout and in the page controller.

**Comment by poi33** [comment]
Suggested change: 
```
if (region) {
        // getting the index of component from string like '/main/0/left/1'
        const cmpIndex = parseInt(cmp.path.split("/")[2])
        region.components.splice(cmpIndex, 0, cmp);
}
```

**Comment by pmi** [comment]
@poi33 This piece of code gets the component index inside a region, not a region index.

**Comment by poi33** [comment]
@pmi sorry my misunderstandig. I hope you still understood the problem.

**Comment by pmi** [comment]
I assume first region is used for both components ? :)
