### ISSUE TITLE
Opening a text component in nested region with other component throws errors

### ISSUE THREAD

**Issue by poi33** [enonic/nextjs-enonic-demo#311]
![image](https://user-images.githubusercontent.com/3340349/176876692-9ff8d3d5-4936-4f12-b1fe-3592ea47a87a.png)

When you have a text component and try to edit it, the next server will return an error

**Comment by poi33** [comment]
Noticed that the order of element probably is incorrect. Since deleting one of the component resulted in the wrong component being removed. Might be related to #307 ?

**Comment by pmi** [comment]
Yep, looks like that was caused by #307 
Can you confirm it's gone in the latest next branch @poi33 ?

**Comment by poi33** [comment]
Using the next branch this is no longer an issue
