### ISSUE TITLE
Macroes inside parts don't render

### ISSUE THREAD

**Issue by poi33** [enonic/nextjs-enonic-demo#354]
When using the macro the output is not shown and looks like: 

`<editor-macro data-macro-name="button" data-macro-ref="{_id}"></editor-macro>`

![Image](https://user-images.githubusercontent.com/3340349/182862598-078af8cb-9b7c-49f9-8d7e-ef685db3deeb.png)

```
<p>
    <br>
    <editor-macro data-macro-name="button" data-macro-ref="6aa74b07-b7da-49cf-9681-dabc05761251"></editor-macro> 
    test
</p>
```

While a straight text component with a macro on the main page renders correctly: 

![Image](https://user-images.githubusercontent.com/3340349/182862970-59a93295-11b0-4413-a77e-46ce8667898f.png)

**Comment by poi33** [comment]
I tried to print out the processed macro. And it has the same <editor-macro> tag. 
Could this be a bug in guillotine?

**Comment by pmi** [comment]
> I tried to print out the processed macro. And it has the same tag. Could this be a bug in guillotine?

No, this simply has not been implemented for parts
