### ISSUE TITLE
Issue with including part query in macro

### ISSUE THREAD

**Issue by poi33** [enonic/nextjs-enonic-demo#423]
I have a TextArea in a part configuration. 
This textArea can have macroes inside it. 

Lets say the field is `text` 

Then the query for the part needs to include:
```
text (processHtml:{}) {
    processedHtml
    macros {
                    ref
                    name
                    descriptor
                    <Insert the config for every macro in the system>
                }
    }
}
```

Now this will be too much to handle manually. Especially since the system can have any macro number of `TextArea` s or macroes. 

Luckely the `src\_enonicAdapter\guillotine\getMetaData.ts` includes a function for getting them: `RichTextQuery`. 

Now the does not work to include it a part query? It looks like the ComponentRegistry (defined in _mapping) is not include the macroes at the same stage? 
So the `RichTextQuery` cant be used inside querys that get registered to the ComponentRegistry? 
I would assume the ComponentRegistry was available when the macroes are defined higher up then the parts, but they don't seem to be registred at all?

**Comment by pmi** [comment]
To make sure that macros are available in the queries 2 things need to be satisfied:

- Macros need to be registered first (There is a comment about that in _mappings.ts)
- queries that use use richTextQuery need to be converted to functions to control when they are invoked (There is a comment about that in getMetaData.ts next to richTextQuery). It may actually work without that, but it's safer this way.

So to use macros in part config you need to register your macros first and then use richTextQuery:

```
ComponentRegistry.addMacro(`${APP_NAME}:panel2`, macroPanelConfig);

const childListConfig = () => `{
        sorting 
        ${richTextQuery('desc')}
    }`

ComponentRegistry.addPart(`${APP_NAME}:child-list`, {
    query: getChildList,
    processor: childListProcessor,
    view: ChildList,
    configQuery: childListConfig()
});
```

**Comment by poi33** [comment]
@pmi I did this, but i thought it was a hacky way of doing it. 
And when applying a change to the part config they show up as missing components.

**Comment by pmi** [comment]
@poi33 Those are not hacks, those are foundations of javascript 😆 

The change showed missing because of lacking mappings import in _component.ts file that I fixed today, so that should not be an issue any more !

**Comment by poi33** [comment]
Nice, I'll check if it works today 🎉
